name: CICD

on:
  push:
    tags: 
      - '*'

jobs:
  CICD:
    runs-on: ubuntu-latest
    env:
      DockerImageName: bakayarusama/duende-login:${{  github.ref_name }}

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Build Docker image
      working-directory: /home/runner/work/Duende/Duende
      run: docker build -t $DockerImageName .

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} 
             -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Publish Docker image
      run: docker push $DockerImageName